name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      ##CreateAPP - yarn release
      - name: Install yarn
        run: npm install -g yarn

      - name: YARN install
        run: yarn install

      ##build
      - name: YARN Build
        run: yarn compile
        env:
          MS_APP_ID: ${{ secrets.MS_APP_ID }}
          MS_APP_SECRET: ${{ secrets.MS_APP_SECRET }}
          MS_APP_URL: ${{ secrets.MS_APP_URL }}
          VERSION: '1.0.0'

      ##ActionRelease - zip
      # - uses: actions/upload-artifact@v1
      #   name: Action-Upload-MacOS1
      #   if: matrix.os == 'macos-latest'
      #   with:
      #     name: MacOS Release
      #     path: '.'

      # - uses: actions/upload-artifact@v1
      #   name: Action-Upload-Windows1
      #   if: matrix.os == 'windows-latest'
      #   with:
      #     name: Windows Release
      #     path: '.'

      - uses: actions/upload-artifact@v1
        name: Action-Upload-Ubuntu1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Linux Release
          path: '.'
